# <font color="red"> **NUMPY** </font> 

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
print(a.reshape(3,1))

[[1]
 [2]
 [3]]


In [6]:
print(a.reshape(1,3))

[[1 2 3]]


In [7]:
print(a.size)

3


In [8]:
type(a)

numpy.ndarray

In [9]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
sifir = np.zeros((2,2))
print(sifir)

[[0. 0.]
 [0. 0.]]


In [11]:
ones = np.ones((3,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
ones[2,3] = 5
ones[0,4] = 10
ones[1,1] = 31
print(ones)

[[ 1.  1.  1.  1. 10.]
 [ 1. 31.  1.  1.  1.]
 [ 1.  1.  1.  5.  1.]]


In [13]:
array = np.arange(5, 56, 10)   #ARANGE IS NOT ARRANGE !!!
print(array)

[ 5 15 25 35 45 55]


In [14]:
print(array.reshape(2,3))

[[ 5 15 25]
 [35 45 55]]


In [15]:
c = np.array([1,2,3])
d = np.array([4,5,6])

print(c + d)

[5 7 9]


In [16]:
print(c ** 2)

[1 4 9]


In [17]:
print(np.sin(c))

[0.84147098 0.90929743 0.14112001]


In [18]:
print(c > 2)

[False False  True]


In [19]:
a = np.array([0,1,2,3,4,5,6,7,8])
print(a[0:7:2])

[0 2 4 6]


In [20]:
print(a[::-1])    #reverse

[8 7 6 5 4 3 2 1 0]


In [21]:
a = a.reshape((3,3))

In [22]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [23]:
a = a.ravel()
print(a)

[0 1 2 3 4 5 6 7 8]


# <font color="red"> **PANDAS** </font> 

In [41]:
import pandas as pd

In [42]:
dictionary = {
              "NAME" :["cagatay", "orhan", "umit", "bekir", "didem", "berk", "jack", "galloway", "ryan"],
              "AGE" : [22, 54, 53, 30, 23, 21,31, 58, 69],
              "SALARY" : [2000, 3000, 1000, 4000, 500, 200, 300, 500, 600]
              }

df = pd.DataFrame(dictionary)

In [43]:
df

NAME  AGE  SALARY
0   cagatay   22    2000
1     orhan   54    3000
2      umit   53    1000
3     bekir   30    4000
4     didem   23     500
5      berk   21     200
6      jack   31     300
7  galloway   58     500
8      ryan   69     600

In [44]:
df.head()  #first 5 data

NAME  AGE  SALARY
0  cagatay   22    2000
1    orhan   54    3000
2     umit   53    1000
3    bekir   30    4000
4    didem   23     500

In [45]:
df.tail()   #last 5 data

NAME  AGE  SALARY
4     didem   23     500
5      berk   21     200
6      jack   31     300
7  galloway   58     500
8      ryan   69     600

In [46]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   NAME    9 non-null      object
 1   AGE     9 non-null      int64 
 2   SALARY  9 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 344.0+ bytes
None


In [47]:
print(df.dtypes)

NAME      object
AGE        int64
SALARY     int64
dtype: object


In [48]:
print(df.describe())    #count : entry size, mean : mean, std: standard deviation, etc.     #so describe gives more numerical information comparing to info()

             AGE       SALARY
count   9.000000     9.000000
mean   40.111111  1344.444444
std    18.319692  1356.568383
min    21.000000   200.000000
25%    23.000000   500.000000
50%    31.000000   600.000000
75%    54.000000  2000.000000
max    69.000000  4000.000000


In [49]:
df["AGE"]

0    22
1    54
2    53
3    30
4    23
5    21
6    31
7    58
8    69
Name: AGE, dtype: int64

In [50]:
df.AGE

0    22
1    54
2    53
3    30
4    23
5    21
6    31
7    58
8    69
Name: AGE, dtype: int64

In [51]:
df["NEW"] = [9,2,0,3,4,5,6,1,10]

In [52]:
df

NAME  AGE  SALARY  NEW
0   cagatay   22    2000    9
1     orhan   54    3000    2
2      umit   53    1000    0
3     bekir   30    4000    3
4     didem   23     500    4
5      berk   21     200    5
6      jack   31     300    6
7  galloway   58     500    1
8      ryan   69     600   10

In [53]:
print(df.loc[5, "AGE"])

21


In [54]:
print(df.loc[2:5, "NAME"])

2     umit
3    bekir
4    didem
5     berk
Name: NAME, dtype: object


In [55]:
print(df.loc[0:4, "NAME":"SALARY"])

      NAME  AGE  SALARY
0  cagatay   22    2000
1    orhan   54    3000
2     umit   53    1000
3    bekir   30    4000
4    didem   23     500


In [56]:
print(df.loc[0:4, "NAME":"SALARY"])

      NAME  AGE  SALARY
0  cagatay   22    2000
1    orhan   54    3000
2     umit   53    1000
3    bekir   30    4000
4    didem   23     500


In [57]:
print(df.iloc[:,2])

0    2000
1    3000
2    1000
3    4000
4     500
5     200
6     300
7     500
8     600
Name: SALARY, dtype: int64


In [58]:
filteredColumns = df[["NAME", "SALARY"]]   #I got specific columns
print(filteredColumns)

       NAME  SALARY
0   cagatay    2000
1     orhan    3000
2      umit    1000
3     bekir    4000
4     didem     500
5      berk     200
6      jack     300
7  galloway     500
8      ryan     600


In [59]:
df

NAME  AGE  SALARY  NEW
0   cagatay   22    2000    9
1     orhan   54    3000    2
2      umit   53    1000    0
3     bekir   30    4000    3
4     didem   23     500    4
5      berk   21     200    5
6      jack   31     300    6
7  galloway   58     500    1
8      ryan   69     600   10

In [61]:
filter = df.SALARY > 1000

In [63]:
print(df[filter])

      NAME  AGE  SALARY  NEW
0  cagatay   22    2000    9
1    orhan   54    3000    2
3    bekir   30    4000    3


In [65]:
filter2 = df.AGE > 29
print(df[filter & filter2])

    NAME  AGE  SALARY  NEW
1  orhan   54    3000    2
3  bekir   30    4000    3


In [67]:
print(filter & filter2)

0    False
1     True
2    False
3     True
4    False
5    False
6    False
7    False
8    False
dtype: bool
